---
elastic_cluster_name: cascade-delight

# Elasticsearch port
elastic_http_port: 9200

# Port nodes use to communicate
elastic_transport_port: 9300

# Elasticsearch suggest no more than 50% of physical RAM
# https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
# Must be in form Xms<integer RAM value><g or m>
# Where g = gibibytes  m = mebibytes
elastic_heap_config_path: /etc/elasticsearch/jvm.options

coord_heap:
  min: '-Xms2g'
  max: '-Xmx2g'

data_heap:
  min: '-Xms4g'
  max: '-Xmx4g'
