---
- name: Get JVM heap values
  set_fact:
    elastic_heap: '{{ coord_heap if target_coord is defined else data_heap }}'

- name: Template elasticsearch.yml file to {{ inventory_hostname }}
  become: yes
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    force: yes
    owner: root
    group: elasticsearch
    mode: 0660 # Make sure to have read access

# Elasticsearch suggest no more than 50% of physical RAM
# https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
- name: Set JVM heap minimum
  become: yes
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '-Xms\d{1,3}[g,G,m,M]'
    line: '{{ elastic_heap.min }}'
    state: present

- name: Set JVM heap maximum
  become: yes
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '-Xmx\d{1,3}[g,G,m,M]'
    line: '{{ elastic_heap.max }}'
    state: present

- name: Start and enable Elasticsearch service
  become: yes
  service:
    name: elasticsearch
    state: stopped

- name: Start and enable Elasticsearch service
  become: yes
  service:
    name: elasticsearch
    enabled: yes
    state: started

- name: Verify contact to elasticsearch
  uri:
    url: 'http://{{ ansible_host }}:{{ elastic_http_port }}/'
    method: GET
