---
- name: Install JRE
  package:
    name: default-jre
    state: present

- name: Download and add Elastic GPG public signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Save the Elasticsearch repository definition
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: present
